import axios, { Axios } from "axios";
const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmd1eWVuVGhhbmgiLCJwaG9uZSI6IiIsImRheXNPZmYiOjEyLCJzdGF0dXMiOiJhY3RpdmUiLCJhdmF0YXIiOiJodHRwczovL2NsYXNzLm5vZGVteS52bi9hcGkvcHVibGljL2ltYWdlcy9sb2dvLnBuZyIsInJvbGUiOiJ1c2VyIiwidGlja2V0IjowLCJsaW5rRkIiOiIiLCJkZWxldGVNb2NrIjpbXSwiZGF0ZU9mQmlydGgiOiIxNjc4MjY3ODQzNjcyIiwiYm90TW9kZWwiOnsiYmFiYmFnZSI6MTAsImN1cmllIjo1LCJkYXZpbmNpIjo1LCJjb2RlRGF2aW5jaSI6NX0sImV4cGlyZWREYXRlIjoiMjAyMy0wMy0xNVQwOTozMDo0My42NzJaIiwiX2lkIjoiNjQyZTc3ZDk0M2YyN2U1MDk5MDgyNmZlIiwiZW1haWwiOiJuZ3V5ZW50aGFuaDI4MDIwMUBnbWFpbC5jb20iLCJ2b3RlcyI6W10sImNyZWF0ZWRBdCI6IjIwMjMtMDQtMDZUMDc6NDI6MTcuODA3WiIsInVwZGF0ZWRBdCI6IjIwMjMtMDQtMDZUMDc6NDI6NTIuMjc1WiIsIl9fdiI6MCwiaWF0IjoxNjgwNzY4OTI1LCJleHAiOjE2ODE2Njg5MjV9.wlXDPXcdREH3CQLBAfOVkg36N9b8pNY8FSCwYWzft0Y'

axios.defaults.baseURL = 'https://class.nodemy.vn/api/mock';
axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
axios.defaults.headers.post['Content-Type'] = 'application/js';

export default axios